[package]
name = "qubes-gui-server"
version = "0.1.0"
edition = "2018"
description = "Qubes GUI protocol server implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
